# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnesGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=200)),
                ('releaseDate', models.DateField(default=datetime.date.today)),
                ('rating', models.IntegerField(default=0)),
                ('description', models.TextField(default='No description')),
            ],
        ),
    ]
