# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_auto_20170926_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snesgame',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
