# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0004_auto_20170926_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snesgame',
            name='display',
        ),
    ]
