# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0005_remove_snesgame_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snesgame',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
